# Generated by Django 3.1.13 on 2021-10-13 11:26

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("guides", "0012_auto_20210914_1333"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidepage",
            name="summary",
            field=wagtail.fields.RichTextField(
                default="", help_text="Summary section for the Guides page"
            ),
        ),
    ]
