# Generated by Django 3.1.14 on 2022-01-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0015_guidepage_background_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidepage',
            name='background_colour',
            field=models.CharField(choices=[('app-section--white', 'white'), ('app-section--grey', 'nhs grey')], default='app-section-white', help_text='set background colour for the section', max_length=45),
        ),
    ]
