# Generated by Django 3.1.14 on 2022-01-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0016_auto_20220105_1553'),
        ('guides', '0015_auto_image_alt_text'),
    ]

    operations = [
    ]
