# Generated by Django 4.0.8 on 2023-03-29 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guides", "0019_alter_guidehubpage_body_alter_guidepage_body_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guidehubpage",
            options={"permissions": [("unpublish", "Can unpublish a published page")]},
        ),
        migrations.AlterModelOptions(
            name="guidepage",
            options={"permissions": [("unpublish", "Can unpublish a published page")]},
        ),
    ]
