# Generated by Django 5.0.9 on 2024-11-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_customdocument_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdocument',
            name='file_size',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
