# Generated by Django 4.0.10 on 2023-07-03 15:18

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0002_alter_navigationsettings_footer_links_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title. Add title if using the URL approach",
                                        required=False,
                                    ),
                                ),
                                (
                                    "url",
                                    wagtail.blocks.CharBlock(
                                        help_text="Only use if page does not exist in CMS",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Single list of elements at the base of the page.",
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer_navigation",
            field=wagtail.fields.StreamField(
                [
                    (
                        "column",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank if no header required.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "page",
                                                    wagtail.blocks.PageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Leave blank to use the page's own title. Add title if using the URL approach",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "url",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Only use if page does not exist in CMS",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Multiple columns of footer links with optional header.",
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="primary_navigation",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title. Add title if using the URL approach",
                                        required=False,
                                    ),
                                ),
                                (
                                    "url",
                                    wagtail.blocks.CharBlock(
                                        help_text="Only use if page does not exist in CMS",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Main site navigation",
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="secondary_navigation",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title. Add title if using the URL approach",
                                        required=False,
                                    ),
                                ),
                                (
                                    "url",
                                    wagtail.blocks.CharBlock(
                                        help_text="Only use if page does not exist in CMS",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Alternative navigation",
                use_json_field=True,
            ),
        ),
    ]
