trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'nhsuk-development-uks'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './scripts/pipeline/clean.sh'