trigger: none

parameters:
  - name: dryrun
    displayName: Dry Run
    type: boolean
    default: false
  - name: review
    displayName: Migrate Review
    type: boolean
    default: false
  - name: integration
    displayName: Migrate Integration
    type: boolean
    default: false
  - name: staging
    displayName: Migrate Staging
    type: boolean
    default: false
  - name: production
    displayName: Migrate Production
    type: boolean
    default: false

stages:
  - stage: Review
    condition: ${{ parameters.review }}
    jobs:
      - deployment: Review
        environment: Review
        strategy:
          runOnce:
            deploy:
              steps:
                - template: postgres/migration-pipeline-steps.yml
                  parameters:
                    env: dev
                    subscriptionId: 07748954-52d6-46ce-95e6-2701bfc715b4 # nhsuk-development
                    appVaultName: dct-crc-v3-vlt-rev-uks
                    singleServerVaultName: dct-camp-cms-vlt-rev-uks
                    singleServerVaultAzureSubscription: dct-development-vault-uks-dct.campaign-resource-centre-v3
                    dryrun: ${{ parameters.dryrun }}

  - stage: Integration
    condition: ${{ parameters.integration }}
    jobs:
      - deployment: Integration
        environment: Integration
        strategy:
          runOnce:
            deploy:
              steps:
                - template: postgres/migration-pipeline-steps.yml
                  parameters:
                    env: int
                    subscriptionId: 07748954-52d6-46ce-95e6-2701bfc715b4 # nhsuk-development (no integration single server - uses dev)
                    appVaultName: dct-crc-v3-vlt-int-uks
                    singleServerVaultName: dct-camp-cms-vlt-int-uks
                    singleServerVaultAzureSubscription: dct-development-vault-uks-dct.campaign-resource-centre-v3
                    dryrun: ${{ parameters.dryrun }}

  - stage: Staging
    condition: ${{ parameters.staging }}
    jobs:
      - deployment: Staging
        environment: Staging
        strategy:
          runOnce:
            deploy:
              steps:
                - template: postgres/migration-pipeline-steps.yml
                  parameters:
                    env: stag
                    subscriptionId: b0787d6a-56e3-4899-bc30-723f9d78899c # nhsuk-staging
                    appVaultName: dct-crc-v3-vlt-stag-uks
                    singleServerVaultName: dct-cmp-cms-vlt-stag-uks
                    singleServerVaultAzureSubscription: dct-staging-vault-uks-dct.campaign-resource-centre-v3
                    dryrun: ${{ parameters.dryrun }}

  - stage: Production
    condition: ${{ parameters.production }}
    jobs:
      - deployment: Approval
        environment: Production
      - deployment: Production
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - template: postgres/migration-pipeline-steps.yml
                  parameters:
                    env: prod
                    subscriptionId: 1e543650-5458-44ea-a3b1-35a6d0d92cc9 # www.nhs.uk
                    appVaultName: dct-crc-v3-vlt-prod-uks
                    singleServerVaultName: dct-cmp-cms-vlt-prod-uks
                    singleServerVaultAzureSubscription: dct-production-vault-uks-dct.campaign-resource-centre-v3
                    dryrun: ${{ parameters.dryrun }}
