services:
  web:
    build:
      context: .
      args:
        BUILD_ENV: ${BUILD_ENV}
    init: true
    environment:
      ALLOWED_HOSTS: 127.0.0.1,0.0.0.0,localhost
      DB_HOST: db
      DB_NAME: campaignresourcecentre
      DB_PASS: campaignresourcecentre
      DB_USER: campaignresourcecentre
      DJANGO_SETTINGS_MODULE: campaignresourcecentre.settings.dev
      MEDIA_DIR: /app/media/
      RECAPTCHA_PRIVATE_KEY: UPDATE_THIS # pragma: allowlist secret
      RECAPTCHA_PUBLIC_KEY: UPDATE_THIS
      REDIS_URL: redis://redis
      SECRET_KEY: local_dev_secret_key
      SECURE_SSL_REDIRECT: 'false'
      STATIC_DIR: /app/static/
      STATIC_URL: /static/
      PARAGON_API_ENDPOINT: ${PARAGON_API_ENDPOINT}
      PARAGON_API_KEY: ${PARAGON_API_KEY}
      PARAGON_MOCK: ${PARAGON_MOCK}
      ADOBE_TRACKING_URL: ${ADOBE_TRACKING_URL}
      COOKIE_DECLARATION: ${COOKIE_DECLARATION}
      AZURE_SEARCH_CONTAINER: ${AZURE_SEARCH_CONTAINER}
      AZURE_SEARCH_ACCESS_KEY: ${AZURE_SEARCH_ACCESS_KEY}
      AZURE_SEARCH_STORAGE_ACCOUNT_NAME: ${AZURE_SEARCH_STORAGE_ACCOUNT_NAME}
      AZURE_SEARCH_PREFIX: ${AZURE_SEARCH_PREFIX}
      AZURE_SEARCH_API_HOST: ${AZURE_SEARCH_API_HOST}
      AZURE_SEARCH_API_VERSION: ${AZURE_SEARCH_API_VERSION}
      AZURE_SEARCH_API_KEY: ${AZURE_SEARCH_API_KEY}
      AZURE_SEARCH_DELETE_API_HOST: ${AZURE_SEARCH_DELETE_API_HOST}
      AZURE_SEARCH_DELETE_API_VERSION: ${AZURE_SEARCH_DELETE_API_VERSION}
      AZURE_SEARCH_FACETS: ${AZURE_SEARCH_FACETS}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY}
      AZURE_CONTAINER: ${AZURE_CONTAINER}
      AZURE_CUSTOM_DOMAIN: ${AZURE_CUSTOM_DOMAIN}
      AZURE_ACCOUNT_NAME: ${AZURE_ACCOUNT_NAME}
      AZURE_ACCOUNT_KEY: ${AZURE_ACCOUNT_KEY}
      AZURE_ACCOUNT_PUBLIC_ENDPOINT: ${AZURE_ACCOUNT_PUBLIC_ENDPOINT}
      AZURE_ACCOUNT_PRIVATE_ENDPOINT: ${AZURE_ACCOUNT_PRIVATE_ENDPOINT}
      CAMPAIGNS_EVENT_API_ENDPOINT: ${CAMPAIGNS_EVENT_API_ENDPOINT}
      COOKIE_CONSENT_CAMPAIGNS: ${COOKIE_CONSENT_CAMPAIGNS}
      PARAGON_ENCRYPTION_KEY: ${PARAGON_ENCRYPTION_KEY}
      PARAGON_SIGN_KEY: ${PARAGON_SIGN_KEY}
      PARAGON_SALT: ${PARAGON_SALT}
      DEBUG: ${DEBUG}
      NOTIFY_DEBUG: ${NOTIFY_DEBUG}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY}
      GUNICORN_CMD_ARGS: ${GUNICORN_CMD_ARGS}
      PHE_PARTNERSHIPS_EMAIL: ${PHE_PARTNERSHIPS_EMAIL}
      REPORTING_ENDPOINT: ${REPORTING_ENDPOINT}
      REPORTING_ENABLED: ${REPORTING_ENABLED}
      TWO_FA: ${TWO_FA}
      WAGTAIL_USER: ${WAGTAIL_USER}
      WAGTAIL_PASSWORD: ${WAGTAIL_PASSWORD}
      PUBTOKEN: ${PUBTOKEN}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      OTEL_SERVICE_NAME: crccms
      OTEL_RESOURCE_ATTRIBUTES: service.namespace=campaigns,service.instance.id=local

    command: tail -f /dev/null # do nothing forever - exec commands elsewhere
    ports:
      - 8000:8000 # runserver
      - 4000:4000 # debugger
    volumes:
      - ./README.md:/app/README.md:delegated,ro
      - ./manage.py:/app/manage.py:delegated,ro
      - ./gunicorn-config.py:/app/gunicorn-config.py:delegated,ro
      - ./campaignresourcecentre:/app/campaignresourcecentre:delegated,rw
      - ./media:/app/media:delegated,rw
      - ./poetry:/app/poetry:delegated,rw
      - ./public:/app/public:delegated,ro
      - ./setup.cfg:/app/setup.cfg:delegated,ro
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    init: true
    environment:
      NODE_ENV: development
      PROXY_HOST: web
      PROXY_PORT: 8000
    volumes:
      # Config files
      - ./.babelrc.js:/home/node/.babelrc.js:delegated,ro
      - ./.editorconfig:/home/node/.editorconfig:delegated,ro
      - ./.eslintignore:/home/node/.eslintignore:delegated,ro
      - ./.eslintrc.js:/home/node/.eslintrc.js:delegated,ro
      - ./.prettierignore:/home/node/.prettierignore:delegated,ro
      - ./.prettierrc.toml:/home/node/.prettierrc.toml:delegated,ro
      - ./.stylelintignore:/home/node/.stylelintignore:delegated,ro
      - ./.stylelintrc.js:/home/node/.stylelintrc.js:delegated,ro
      - ./browsersync.config.js:/home/node/browsersync.config.js:delegated,ro
      - ./package-lock.json:/home/node/package-lock.json:delegated,rw
      - ./package.json:/home/node/package.json:delegated,rw
      - ./webpack.config.js:/home/node/webpack.config.js:delegated,ro
      # Source files
      - ./campaignresourcecentre/static_src:/home/node/campaignresourcecentre/static_src:delegated,ro
    command: tail -f /dev/null # do nothing forever - exec commands elsewhere
    ports:
      - 3000:3000
      - 3001:3001

  db:
    image: postgres:16
    expose:
      - 5432
    environment:
      POSTGRES_DB: campaignresourcecentre
      POSTGRES_USER: campaignresourcecentre
      POSTGRES_PASSWORD: campaignresourcecentre # pragma: allowlist secret
      PGDATABASE: campaignresourcecentre
      PGUSER: campaignresourcecentre
      PGPASSWORD: campaignresourcecentre # pragma: allowlist secret
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./database_dumps:/database_dumps:delegated,rw
    logging:
      driver: none

  redis:
    image: redis:3.0
    expose:
      - 6379
    logging:
      driver: none
