pool:
  vmImage: ubuntu-latest

trigger: none

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - terraform

stages:
  - stage: Test
    condition: eq(variables['Build.Reason'], 'PullRequest')

    displayName: Test
    jobs:
      - job: test
        displayName: Test
        steps:
          - template: azure-pipeline-templates/test.yml
