pool:
  vmImage: 'ubuntu-latest'
trigger:
  branches:
    include:
    - "refs/pull/*/head"

stages:
- stage: Test
  condition: eq(variables['Build.Reason'], 'PullRequest')

  displayName: Test
  jobs:
    - job: test
      displayName: 'Test'
      steps:
        - template: azure-pipeline-templates/test.yml