steps:
  - task: Docker@2
    displayName: 'Docker Build'
    inputs:
      containerRegistry: 'nhsuk acr-dct.campaign-resource-centre-v3'
      dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      repository: '$(repository)'
      command: 'build'
      arguments: '--build-arg BUILD_ENV="production"'
      tags: |
        ${{ parameters.tag }}
  - task: Docker@2
    displayName: 'Docker Push'
    condition: ne('${{ parameters.dryRun }}', 'True')
    inputs:
      containerRegistry: 'nhsuk acr-dct.campaign-resource-centre-v3'
      dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      repository: '$(repository)'
      command: 'push'
      tags: |
        ${{ parameters.tag }}
  - bash: |
      apt install trivy
      trivy image --severity HIGH,CRITICAL  --output $(Build.ArtifactStagingDirectory)/${{ parameters.tag }}-scan.txt --scanners vuln nhsuk.azurecr.io/$(repository):${{ parameters.tag }}
    displayName: 'trivy - bash'
    condition: ne('${{ parameters.dryRun }}', 'True')
  # - task: trivy@1
  #   displayName: 'trivy - task'
  #   condition: and(succeededOrFailed(), ne('${{ parameters.dryRun }}', 'True'))
  #   inputs:
  #     image: nhsuk.azurecr.io/$(repository):${{ parameters.tag }}
  #     # Needed to access private repo 
  #     loginDockerConfig: true
  #     severities: HIGH,CRITICAL
