parameters:
  - name: tag
    type: string
    default: latest
  - name: dryrun
    type: boolean
    default: false

steps:
  - task: Docker@2
    displayName: Docker Build (dctcampaignsacrproduks)
    inputs:
      dockerfile: $(Build.SourcesDirectory)/Dockerfile
      repository: dctcampaignsacrproduks.azurecr.io/dct/crc-cms 
      command: build
      arguments: '--build-arg BUILD_ENV="production"'
      tags: ${{ parameters.tag }},$(Build.SourceVersion)
  - bash: |
      sudo apt-get install wget apt-transport-https gnupg
      wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
      echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
      sudo apt-get update
      sudo apt-get install trivy

      junitTemplate="@$(which trivy | sed 's/bin/local\/share/')/templates/junit.tpl"
      trivy image --severity HIGH,CRITICAL --format template --template $junitTemplate -o trivy-scan.xml --scanners vuln dctcampaignsacrproduks.azurecr.io/dct/crc-cms:${{ parameters.tag }}
    displayName: 'Run Trivy Scan'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: "Publish Scan Results"
    inputs:
      testResultsFiles: "**/trivy-scan.xml"
      testRunTitle: "${{ parameters.tag }} image scan"
      failTaskOnFailedTests: true
  - task: AzureCLI@2
    displayName: Docker Login (dctcampaignsacrproduks)
    inputs:
      azureSubscription: dct-crccms-dev
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: az acr login --name dctcampaignsacrproduks
  - ${{ if parameters.dryrun }}:
      - bash: |
          echo "##vso[task.logissue type=warning;]Running in dryrun mode - skipping image tag push for 'dct/crc-cms:${{ parameters.tag }}'"
          echo "##vso[task.complete result=SucceededWithIssues;]"
        displayName: "Dry Run Warning"
  - task: Docker@2
    displayName: Docker Push (dctcampaignsacrproduks)
    condition: and(succeeded(), ne('${{ lower(parameters.dryRun) }}', 'true'))
    inputs:
      repository: dctcampaignsacrproduks.azurecr.io/dct/crc-cms
      command: push
      tags: ${{ parameters.tag }},$(Build.SourceVersion)
  

