parameters:
  - name: tag
    type: string
    default: latest
  - name: dryrun
    type: boolean
    default: false

steps:
  - task: Docker@2
    displayName: 'Docker Build (nhsuk acr-dct.campaign-resource-centre-v3)'
    inputs:
      containerRegistry: 'nhsuk acr-dct.campaign-resource-centre-v3'
      dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      repository: '$(repository)'
      command: 'build'
      arguments: '--build-arg BUILD_ENV="production"'
      tags: |
        ${{ parameters.tag }}
  - bash: |
      sudo apt-get install wget apt-transport-https gnupg
      wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
      echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
      sudo apt-get update
      sudo apt-get install trivy

      junitTemplate="@$(which trivy | sed 's/bin/local\/share/')/templates/junit.tpl"
      trivy image --severity HIGH,CRITICAL --format template --template $junitTemplate -o trivy-scan.xml --scanners vuln nhsuk.azurecr.io/$(repository):${{ parameters.tag }}
    displayName: 'Run Trivy Scan (nhsuk acr-dct.campaign-resource-centre-v3)'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: "Publish Scan Results"
    inputs:
      testResultsFiles: "**/trivy-scan.xml"
      testRunTitle: "${{ parameters.tag }} image scan"
      failTaskOnFailedTests: true
  - task: Docker@2
    displayName: 'Docker Push (nhsuk acr-dct.campaign-resource-centre-v3) '
    condition: and(succeeded(), ne('${{ parameters.dryRun }}', 'True'))
    inputs:
      containerRegistry: 'nhsuk acr-dct.campaign-resource-centre-v3'
      dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      repository: '$(repository)'
      command: 'push'
      tags: |
        ${{ parameters.tag }}
  - task: Docker@2
    displayName: Docker Build (dctcampaignsacrproduks)
    inputs:
      dockerfile: $(Build.SourcesDirectory)/Dockerfile
      repository: dctcampaignsacrproduks.azurecr.io/dct/crc-cms 
      command: build
      tags: ${{ parameters.tag }},$(Build.SourceVersion)
  - task: AzureCLI@2
    displayName: Docker Login (dctcampaignsacrproduks)
    condition: and(succeeded(), ne('${{ parameters.dryrun }}', 'True'))
    inputs:
      azureSubscription: dct-crccms-dev
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: az acr login --name dctcampaignsacrproduks
  - task: Docker@2
    displayName: Docker Push (dctcampaignsacrproduks)
    condition: and(succeeded(), ne('${{ parameters.dryrun }}', 'True'))
    inputs:
      repository: dctcampaignsacrproduks.azurecr.io/dct/crc-cms
      command: push
      tags: ${{ parameters.tag }},$(Build.SourceVersion)

