pool:
  vmImage: ubuntu-latest

trigger: none
pr: none

# daily midnight backup midnight - this will not run any of the syncing jobs, only the backup
schedules:
  - cron: '0 0 * * *'
    displayName: Daily midnight build
    always: true
    branches:
      include:
        - main

parameters:
  - name: backupProduction
    type: boolean
    default: true
    displayName: Backup Production DB
  - name: syncToReview
    type: boolean
    default: false
    displayName: Sync To Review Env
  - name: syncToIntegration
    type: boolean
    default: false
    displayName: Sync To Integration Env
  - name: syncToStaging
    type: boolean
    default: false
    displayName: Sync To Staging Env

resources:
  - repo: self

stages:
  - stage: CopyFromProdDB
    displayName: Copy Production Database
    jobs:
      - job: ProdDBCopy
        steps:
          - task: AzureKeyVault@2
            displayName: 'Azure Key Vault: dct-crc-kv-app-prod-uks'
            inputs:
              azureSubscription: dct-crccms-prod
              KeyVaultName: dct-crc-kv-app-prod-uks
              SecretsFilter: db-pass, db-name, db-host, db-user
          - template: templates/db-sync-download-dump.yaml
            parameters:
              dumpPrefix: prod
              publishDump: true

  - stage: UploadProdDumpToBlob
    displayName: Backup Production Database
    dependsOn:
      - CopyFromProdDB
    condition: and(succeeded(), eq('${{ parameters.backupProduction }}', 'true'))
    jobs:
      - job: DumpUpload
        steps:
          - template: templates/db-sync-upload-blob.yaml
            parameters:
              azureStorageSubscription: dct-crccms-prod
              StorageAccountNameDbDump: $(StorageAccountNameDbDump)
              BlobStorageKeyDbDump: $(BlobStorageKeyDbDump)
              BlobStorageContainerNameDbDump: $(BlobStorageContainerNameDbDump)
              useArtifact: true
              dumpPrefix: prod

  - stage: CopyToReviewDB
    displayName: Copy to Review Database
    dependsOn:
      - CopyFromProdDB
    condition: and(succeeded(), eq('${{ parameters.syncToReview }}', true))
    jobs:
      - job: ReviewPaste
        steps:
          - template: templates/db-sync-env-sync.yaml
            parameters:
              azureStorageSubscription: nhsuk-dct-rg-dev-uks.campaign-resource-centre-v3
              azureVaultSubscription: dct-crccms-dev
              VaultId: dct-crc-kv-app-dev-uks
              environment: review
              env: dev

  - stage: CopyToIntegrationDB
    displayName: Copy to Integration Database
    dependsOn:
      - CopyFromProdDB
    condition: and(succeeded(), eq('${{ parameters.syncToIntegration }}', true))
    jobs:
      - job: IntegrationPaste
        steps:
          - template: templates/db-sync-env-sync.yaml
            parameters:
              azureStorageSubscription: nhsuk-dct-rg-dev-uks.campaign-resource-centre-v3
              azureVaultSubscription: dct-crccms-int
              VaultId: dct-crc-kv-app-int-uks
              environment: integration
              env: int

  - stage: CopyToStagingDB
    displayName: Copy to Staging Database
    dependsOn:
      - CopyFromProdDB
    condition: and(succeeded(), eq('${{ parameters.syncToStaging }}', true))
    jobs:
      - deployment: approval
        environment: staging
      - job: StagingPaste
        steps:
          - template: templates/db-sync-env-sync.yaml
            parameters:
              azureVaultSubscription: dct-crccms-stag
              azureStorageSubscription: dct-crccms-stag
              VaultId: dct-crc-kv-app-stag-uks
              environment: staging
              env: stag
