apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}-ing
{{ include "charts.labels" . | indent 4 }}
spec:
  {{- $values := .Values }}
  {{ if .Values.hostUrlCertSecretName }}
  tls:
    - hosts:
        - {{ .Values.hostUrl }}
      secretName: {{ .Values.hostUrlCertSecretName }}
  {{ end }}
  rules:
  {{ if .Values.hostUrl }}
  - host: {{ .Values.hostUrl }}
    http:
      paths:
        {{- range .Values.hostUrlPaths }}
        - path: {{ . | quote }}
          pathType: ImplementationSpecific
          backend:
            service:
                name: {{ $values.appName }}-{{ $values.appFramework }}-svc
                port:
                  number: {{ $values.appPort }}
        {{- end }}
  {{ end }}
  {{ if .Values.drHostUrl }}
  - host: {{ .Values.drHostUrl }}
    http:
      paths:
        {{- range .Values.hostUrlPaths }}
        - path: {{ . | quote }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $values.appName }}-{{ $values.appFramework }}-svc
              port:
                number: {{ $values.appPort }}
        {{- end }}
  {{ end }}
  {{ if .Values.intHostUrl }}
  - host: {{ .Values.intHostUrl }}
    http:
      paths:
        {{- range .Values.intHostUrlPaths }}
        - path: {{ . | quote }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $values.appName }}-{{ $values.appFramework }}-svc
              port:
                number: {{ $values.appPort }}
        {{- end }}
  {{ end }}
