# Generated by Django 3.1.8 on 2021-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(
                choices=[
                    ("director", "Director / Board Member / CEO"),
                    ("admin", "Administration"),
                    ("comms", "Communications"),
                    ("education", "Education and Teaching"),
                    ("marketing", "Marketing"),
                    ("health:improvement", "Health Improvement / Public Health"),
                    ("health:gpspecialistnurse", "GP, Specialist, Nurse and HCA"),
                    ("health:pharmacy", "Pharmacy"),
                    ("health:management", "Practice Management"),
                    ("health:other", "Other"),
                    ("hr", "HR / Training / Organisational Development"),
                    (
                        "community",
                        "Community and Social Services / Charity / Volunteering",
                    ),
                    ("student", "Student / Unemployed / Retired"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organisation",
            field=models.CharField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="postcode",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="second_name",
            field=models.CharField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="terms",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=254),
        ),
    ]
