# Generated by Django 3.1.8 on 2021-04-27 15:11

import campaignresourcecentre.page_lifecycle.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcepage",
            name="last_reviewed",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="resourcepage",
            name="next_review",
            field=models.DateField(
                default=campaignresourcecentre.page_lifecycle.utils.calculate_next_review_date
            ),
        ),
    ]
