# Generated by Django 3.1.8 on 2021-05-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0002_add_lifecycle_mixin"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcepage",
            name="taxonomy_json",
            field=models.TextField(blank=True, null=True),
        ),
    ]
