# Generated by Django 3.1.11 on 2021-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0006_permission_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceitem",
            name="document_content",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
    ]
