# Generated by Django 3.1.13 on 2021-09-17 11:19

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0008_auto_20210721_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcepage",
            name="summary",
            field=wagtail.core.fields.RichTextField(default=""),
            preserve_default=False,
        ),
    ]
