# Generated by Django 3.1.13 on 2021-09-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0009_resourcepage_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceitem",
            name="image_alt_text",
            field=models.CharField(
                blank=True,
                help_text="Alt text for the image.",
                max_length=50,
                null=True,
            ),
        ),
    ]
