# Generated by Django 3.1.13 on 2021-10-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0011_auto_20211004_1215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcepage",
            name="summary",
            field=models.TextField(
                help_text="A short line of text for display on campaign hub"
            ),
        ),
    ]
