# Generated by Django 3.1.13 on 2022-02-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0013_auto_20211029_0934"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcepage",
            name="permission_role",
            field=models.CharField(
                choices=[
                    ("all", "Open access"),
                    ("standard", "Standard"),
                    ("uber", "Uber"),
                ],
                default="all",
                max_length=10,
            ),
        ),
    ]
