# Generated by Django 4.0.4 on 2022-08-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0014_open_access_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceitem",
            name="image_alt_text",
            field=models.CharField(
                blank=True,
                help_text="Leave blank if the image is purely decorative. Most images on CRC will not require alt text.",
                max_length=50,
                null=True,
            ),
        ),
    ]
