# Generated by Django 4.0.8 on 2023-01-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0015_alter_resourceitem_image_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcepage",
            name="permission_role",
            field=models.CharField(
                choices=[
                    ("all", "Open access"),
                    ("standard", "Standard"),
                    ("uber", "Uber"),
                ],
                default="standard",
                max_length=10,
            ),
        ),
    ]
