# Generated by Django 3.1.8 on 2021-04-21 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaignupdate",
            old_name="campaign",
            new_name="page",
        ),
        migrations.AlterField(
            model_name="campaignupdate",
            name="link_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose a page to link to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns_campaignupdate_link_page",
                to="wagtailcore.page",
            ),
        ),
    ]
