# Generated by Django 3.1.8 on 2021-04-22 15:08

import campaignresourcecentre.page_lifecycle.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_auto_20210421_1435"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignpage",
            name="last_reviewed",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="campaignpage",
            name="next_review",
            field=models.DateField(
                default=campaignresourcecentre.page_lifecycle.utils.calculate_next_review_date
            ),
        ),
    ]
