# Generated by Django 3.1.8 on 2021-05-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_auto_20210422_1608"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignpage",
            name="taxonomy_json",
            field=models.TextField(blank=True, null=True),
        ),
    ]
