# Generated by Django 3.1.13 on 2021-08-03 16:16

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0004_campaignpage_taxonomy_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignpage",
            name="body",
            field=wagtail.fields.StreamField([], blank=True),
        ),
    ]
