# Generated by Django 3.1.13 on 2021-08-10 15:03

import campaignresourcecentre.campaigns.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0007_campaignhubpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignhubpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Card_group",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Full-width"),
                                            ("one-half", "One-half"),
                                            ("one-third", "One-third"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "card_basic",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "heading",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "heading_level",
                                                            wagtail.blocks.IntegerBlock(
                                                                default=3,
                                                                help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                max_value=6,
                                                                min_value=2,
                                                            ),
                                                        ),
                                                        (
                                                            "heading_size",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Default"),
                                                                    ("small", "Small"),
                                                                    (
                                                                        "medium",
                                                                        "Medium",
                                                                    ),
                                                                    ("large", "Large"),
                                                                ],
                                                                help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "body",
                                                            wagtail.blocks.RichTextBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "card_clickable",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "heading",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "heading_level",
                                                            wagtail.blocks.IntegerBlock(
                                                                default=3,
                                                                help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                max_value=6,
                                                                min_value=2,
                                                            ),
                                                        ),
                                                        (
                                                            "heading_size",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Default"),
                                                                    ("small", "Small"),
                                                                    (
                                                                        "medium",
                                                                        "Medium",
                                                                    ),
                                                                    ("large", "Large"),
                                                                ],
                                                                help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "body",
                                                            wagtail.blocks.RichTextBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "internal_page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                help_text="Interal Page Link for the card",
                                                                label="Internal Page",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            wagtail.blocks.URLBlock(
                                                                help_text="External Link for the card",
                                                                label="URL",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "card_image",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "heading",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "heading_level",
                                                            wagtail.blocks.IntegerBlock(
                                                                default=3,
                                                                help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                max_value=6,
                                                                min_value=2,
                                                            ),
                                                        ),
                                                        (
                                                            "heading_size",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Default"),
                                                                    ("small", "Small"),
                                                                    (
                                                                        "medium",
                                                                        "Medium",
                                                                    ),
                                                                    ("large", "Large"),
                                                                ],
                                                                help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "body",
                                                            wagtail.blocks.RichTextBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "content_image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                label="Image",
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "alt_text",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            wagtail.blocks.URLBlock(
                                                                help_text="Optional, if there is a link the entire card will be clickable.",
                                                                label="URL",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "internal_page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                help_text="Optional, if there is a link the entire card will be clickable.",
                                                                label="Internal Page",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "card_feature",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "feature_heading",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "heading_level",
                                                            wagtail.blocks.IntegerBlock(
                                                                default=3,
                                                                help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                max_value=6,
                                                                min_value=2,
                                                            ),
                                                        ),
                                                        (
                                                            "heading_size",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Default"),
                                                                    ("small", "Small"),
                                                                    (
                                                                        "medium",
                                                                        "Medium",
                                                                    ),
                                                                    ("large", "Large"),
                                                                ],
                                                                help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "body",
                                                            wagtail.blocks.RichTextBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "Accordian",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "accordian_sections",
                                    wagtail.blocks.ListBlock(
                                        campaignresourcecentre.campaigns.blocks.CampaignAccordianBlock
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="campaignpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "Card_group",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "column",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Full-width"),
                                            ("one-half", "One-half"),
                                            ("one-third", "One-third"),
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "body",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "card_basic",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "heading",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "heading_level",
                                                            wagtail.blocks.IntegerBlock(
                                                                default=3,
                                                                help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                max_value=6,
                                                                min_value=2,
                                                            ),
                                                        ),
                                                        (
                                                            "heading_size",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Default"),
                                                                    ("small", "Small"),
                                                                    (
                                                                        "medium",
                                                                        "Medium",
                                                                    ),
                                                                    ("large", "Large"),
                                                                ],
                                                                help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "body",
                                                            wagtail.blocks.RichTextBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "card_clickable",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "heading",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "heading_level",
                                                            wagtail.blocks.IntegerBlock(
                                                                default=3,
                                                                help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                max_value=6,
                                                                min_value=2,
                                                            ),
                                                        ),
                                                        (
                                                            "heading_size",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Default"),
                                                                    ("small", "Small"),
                                                                    (
                                                                        "medium",
                                                                        "Medium",
                                                                    ),
                                                                    ("large", "Large"),
                                                                ],
                                                                help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "body",
                                                            wagtail.blocks.RichTextBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "internal_page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                help_text="Interal Page Link for the card",
                                                                label="Internal Page",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            wagtail.blocks.URLBlock(
                                                                help_text="External Link for the card",
                                                                label="URL",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "card_image",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "heading",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "heading_level",
                                                            wagtail.blocks.IntegerBlock(
                                                                default=3,
                                                                help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                max_value=6,
                                                                min_value=2,
                                                            ),
                                                        ),
                                                        (
                                                            "heading_size",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Default"),
                                                                    ("small", "Small"),
                                                                    (
                                                                        "medium",
                                                                        "Medium",
                                                                    ),
                                                                    ("large", "Large"),
                                                                ],
                                                                help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "body",
                                                            wagtail.blocks.RichTextBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "content_image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                label="Image",
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "alt_text",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "url",
                                                            wagtail.blocks.URLBlock(
                                                                help_text="Optional, if there is a link the entire card will be clickable.",
                                                                label="URL",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "internal_page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                help_text="Optional, if there is a link the entire card will be clickable.",
                                                                label="Internal Page",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "card_feature",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "feature_heading",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "heading_level",
                                                            wagtail.blocks.IntegerBlock(
                                                                default=3,
                                                                help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                max_value=6,
                                                                min_value=2,
                                                            ),
                                                        ),
                                                        (
                                                            "heading_size",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("", "Default"),
                                                                    ("small", "Small"),
                                                                    (
                                                                        "medium",
                                                                        "Medium",
                                                                    ),
                                                                    ("large", "Large"),
                                                                ],
                                                                help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "body",
                                                            wagtail.blocks.RichTextBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ],
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "Accordian",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "accordian_sections",
                                    wagtail.blocks.ListBlock(
                                        campaignresourcecentre.campaigns.blocks.CampaignAccordianBlock
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
    ]
