# Generated by Django 3.1.13 on 2021-09-16 09:49

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0015_auto_20210914_1333"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignpage",
            name="description",
            field=wagtail.core.fields.RichTextField(default=""),
            preserve_default=False,
        ),
    ]
