# Generated by Django 3.1.13 on 2021-10-04 11:15

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_campaignpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpage',
            name='description',
            field=wagtail.core.fields.RichTextField(help_text='Introduction section for the resource page'),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='summary',
            field=wagtail.core.fields.RichTextField(help_text='Short line of text for display on the campaign page'),
        ),
    ]
