# Generated by Django 3.1.13 on 2021-10-25 17:26

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_auto_20211004_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpage',
            name='description',
            field=wagtail.core.fields.RichTextField(help_text='Introduction section for the campaign page. This is limited to 400 characters to make sure the page loads properly on frontend. Please preview the page before you publish as this depends on length of the below image and may alter the page overall design.', max_length=480),
        ),
    ]
