# Generated by Django 3.1.13 on 2021-12-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0019_auto_20211105_1244"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignupdate",
            name="image_alt_text",
            field=models.TextField(blank=True),
        ),
    ]
