# Generated by Django 3.1.14 on 2022-01-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_campaignupdate_image_alt_text'),
        ('campaigns', '0023_campaignhubpage_campaign_updates_bg_colour'),
    ]

    operations = [
    ]
