# Generated by Django 3.1.13 on 2022-02-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0024_merge_20220106_1446"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignhubpage",
            name="campaign_updates_bg_colour",
            field=models.CharField(
                choices=[
                    ("app-section--white", "white"),
                    ("app-section--grey", "nhs grey"),
                ],
                default="app-section--white",
                help_text="set background colour for the section",
                max_length=45,
            ),
        ),
    ]
