# Generated by Django 4.0.8 on 2023-03-29 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0030_alter_campaignpage_campaign_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignhubpage",
            options={"permissions": [("unpublish", "Can unpublish a published page")]},
        ),
    ]
