# Generated by Django 5.2.11 on 2026-02-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0035_topic_code_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="show_in_filter",
            field=models.BooleanField(
                default=True,
                help_text="Show this topic as a filter option on the campaigns page.",
            ),
        ),
    ]
