# Generated by Django 5.0.14 on 2025-06-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0005_featureflags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="featureflags",
            options={"verbose_name": "Feature flags"},
        ),
        migrations.AddField(
            model_name="featureflags",
            name="sz_email_year_groups",
            field=models.BooleanField(
                default=False,
                help_text="Enable or disable the School Zone email year groups feature flag",
                verbose_name="School Zone email year groups (requires School Zone email journey)",
            ),
        ),
        migrations.AlterField(
            model_name="featureflags",
            name="sz_email_variant",
            field=models.BooleanField(
                default=False,
                help_text="Enable or disable the School Zone email signup journey variant",
                verbose_name="School Zone email journey",
            ),
        ),
    ]
