# Generated by Django 5.2.9 on 2026-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0006_alter_featureflags_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="featureflags",
            options={
                "permissions": [
                    (
                        "change_ordering_history_flags",
                        "Can change ordering and order history feature flags",
                    )
                ],
                "verbose_name": "Feature flags",
            },
        ),
        migrations.AddField(
            model_name="featureflags",
            name="disable_order_history",
            field=models.BooleanField(
                default=False,
                help_text="Enable this flag to hide the order history feature. Will return 404 for order history page.",
                verbose_name="Disable order history",
            ),
        ),
        migrations.AddField(
            model_name="featureflags",
            name="disable_ordering_and_checkout",
            field=models.BooleanField(
                default=False,
                help_text="Enable this flag to hide the basket and checkout process.",
                verbose_name="Disable ordering and checkout",
            ),
        ),
    ]
