# Generated by Django 5.2.12 on 2026-04-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0007_alter_featureflags_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureflags",
            name="notification_banner_campaign_page",
            field=models.BooleanField(
                default=False,
                help_text="Enable this flag to show a notification banner on an individual campaign page.",
                verbose_name="Enable notification banner on campaign page",
            ),
        ),
        migrations.AddField(
            model_name="featureflags",
            name="notification_banner_campaigns_page",
            field=models.BooleanField(
                default=False,
                help_text="Enable this flag to show a notification banner on the main 'Campaigns' page.",
                verbose_name="Enable notification banner on campaigns page",
            ),
        ),
        migrations.AddField(
            model_name="featureflags",
            name="notification_banner_search_results",
            field=models.BooleanField(
                default=False,
                help_text="Enable this flag to show a notification banner on the search results page.",
                verbose_name="Enable notification banner on search results page",
            ),
        ),
    ]
