# Generated by Django 5.2.12 on 2026-04-17 16:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0007_alter_featureflags_options_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationBanner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Important",
                        help_text="The heading displayed in the banner header.",
                        max_length=255,
                    ),
                ),
                (
                    "heading_level",
                    models.CharField(
                        choices=[
                            ("h1", "H1"),
                            ("h2", "H2"),
                            ("h3", "H3"),
                            ("h4", "H4"),
                        ],
                        default="h2",
                        help_text="The heading level for the banner header.",
                        max_length=2,
                    ),
                ),
                (
                    "content",
                    wagtail.fields.RichTextField(
                        default="We have moved to a digital-only service and we no longer provide printed resources for our campaigns",
                        help_text="The content displayed in the banner body.",
                    ),
                ),
                (
                    "show_on_campaigns_page",
                    models.BooleanField(
                        default=False,
                        help_text="Show the notification banner on the main campaigns listing page.",
                        verbose_name="Show on campaigns page",
                    ),
                ),
                (
                    "show_on_campaign_page",
                    models.BooleanField(
                        default=False,
                        help_text="Show the notification banner on individual campaign pages.",
                        verbose_name="Show on campaign pages",
                    ),
                ),
                (
                    "show_on_search_results",
                    models.BooleanField(
                        default=False,
                        help_text="Show the notification banner on the search results page.",
                        verbose_name="Show on search results page",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification banner",
            },
        ),
    ]
