locals {
  org            = "dct"
  app            = "crccms"
  short_app_name = "crc"
  environment    = "dev"
  region         = "uks"

  init_args = [
    "bash",
    "-c",
    "bash ./initializer-entrypoint.sh"
  ]

  init_secrets = [
    "DB_HOST",
    "DB_NAME",
    "DB_PASS",
    "DB_USER",
    "DEBUG",
    "DJANGO_SETTINGS_MODULE",
    "GUNICORN_CMD_ARGS",
    "NOTIFY_DEBUG",
    "PARAGON_API_ENDPOINT",
    "PARAGON_API_KEY",
    "PARAGON_ENCRYPTION_KEY",
    "PARAGON_MOCK",
    "PARAGON_SALT",
    "PARAGON_SIGN_KEY",
    "PRIMARY_HOST",
    "PUBTOKEN",
    "REDIS_URL",
    "REPORTING_ENABLED",
    "REPORTING_ENDPOINT",
    "SECRET_KEY",
    "STATIC_DIR",
    "STATIC_URL",
    "TWO_FA",
    "WAGTAIL_PASSWORD",
    "WAGTAIL_USER",
    "WEB_CONCURRENCY",
    "AUTOWRAPT_BOOTSTRAP",
    "INSTANA_AGENT_HOST"
  ]

  init_config = {
  }

  app_secrets = [
    "ADOBE_TRACKING_URL",
    "ALLOWED_HOSTS",
    "AZURE_ACCOUNT_KEY",
    "AZURE_ACCOUNT_NAME",
    "AZURE_CONTAINER",
    "AZURE_CUSTOM_DOMAIN",
    "AZURE_SEARCH_ACCESS_KEY",
    "AZURE_SEARCH_API_HOST",
    "AZURE_SEARCH_API_KEY",
    "AZURE_SEARCH_API_VERSION",
    "AZURE_SEARCH_CONTAINER",
    "AZURE_SEARCH_DELETE_API_HOST",
    "AZURE_SEARCH_DELETE_API_VERSION",
    "AZURE_SEARCH_FACETS",
    "AZURE_SEARCH_PREFIX",
    "AZURE_SEARCH_STORAGE_ACCOUNT_NAME",
    "CAMPAIGNS_EVENT_API_ENDPOINT",
    "COOKIE_CONSENT_CAMPAIGNS",
    "COOKIE_DECLARATION",
    "DB_HOST",
    "DB_NAME",
    "DB_PASS",
    "DB_USER",
    "DEBUG",
    "DJANGO_SETTINGS_MODULE",
    "GUNICORN_CMD_ARGS",
    "MEDIA_DIR",
    "NOTIFY_API_KEY",
    "NOTIFY_DEBUG",
    "PARAGON_API_ENDPOINT",
    "PARAGON_API_KEY",
    "PARAGON_ENCRYPTION_KEY",
    "PARAGON_MOCK",
    "PARAGON_SALT",
    "PARAGON_SIGN_KEY",
    "PHE_PARTNERSHIPS_EMAIL",
    "PRIMARY_HOST",
    "PUBTOKEN",
    "REDIS_URL",
    "REPORTING_ENABLED",
    "REPORTING_ENDPOINT",
    "SECRET_KEY",
    "SECURE_SSL_REDIRECT",
    "STATIC_DIR",
    "STATIC_URL",
    "TWO_FA",
    "WAGTAIL_PASSWORD",
    "WAGTAIL_USER",
    "WEB_CONCURRENCY",
    "AUTOWRAPT_BOOTSTRAP",
    "INSTANA_AGENT_HOST",
    "APPLICATIONINSIGHTS_CONNECTION_STRING",
    "OTEL_SERVICE_NAME",
    "OTEL_RESOURCE_ATTRIBUTES"
  ]
}
