# Generated by Django 3.1.8 on 2021-04-21 13:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("images", "0002_customimage_file_hash"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="strapline",
        ),
        migrations.AddField(
            model_name="homepage",
            name="campaign_updates_heading",
            field=models.CharField(
                blank=True,
                default="Latest updates",
                help_text="This is only shown if there are campaign updates to display.",
                max_length=75,
                verbose_name="Heading",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="introduction",
            field=wagtail.fields.RichTextField(default=""),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CampaignUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "link_url",
                    models.URLField(blank=True, help_text="Enter a URL to link to."),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True,
                        help_text="Enter the text for the link. This is required for external URLs. If an internal page is chosen and this field is blank the page title will be shown",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Enter the text to display."),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Choose an image to display.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose a page to link to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_campaignupdate_link_page",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_updates",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
