# Generated by Django 3.1.13 on 2021-08-05 14:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20210421_1435"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "content_link",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("title", wagtail.core.blocks.CharBlock()),
                                ("text", wagtail.core.blocks.RichTextBlock()),
                                ("button_text", wagtail.core.blocks.CharBlock()),
                                ("button_url", wagtail.core.blocks.URLBlock()),
                            ]
                        ),
                    )
                ],
                default="",
            ),
            preserve_default=False,
        ),
    ]
