# Generated by Django 3.1.13 on 2021-08-06 10:19

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "content_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.RichTextBlock()),
                                ("button_text", wagtail.blocks.CharBlock()),
                                ("button_url", wagtail.blocks.URLBlock()),
                            ]
                        ),
                    )
                ]
            ),
        ),
    ]
