# Generated by Django 3.1.13 on 2021-08-10 12:18

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_auto_20210806_1737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "content_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("text", wagtail.blocks.RichTextBlock()),
                                ("button_text", wagtail.blocks.CharBlock()),
                                ("button_url", wagtail.blocks.URLBlock()),
                            ]
                        ),
                    ),
                    (
                        "Common_Blocks",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "Card_group",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "column",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("", "Full-width"),
                                                        ("one-half", "One-half"),
                                                        ("one-third", "One-third"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "body",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "card_basic",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "heading",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_level",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            default=3,
                                                                            help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                            max_value=6,
                                                                            min_value=2,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_size",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "",
                                                                                    "Default",
                                                                                ),
                                                                                (
                                                                                    "small",
                                                                                    "Small",
                                                                                ),
                                                                                (
                                                                                    "medium",
                                                                                    "Medium",
                                                                                ),
                                                                                (
                                                                                    "large",
                                                                                    "Large",
                                                                                ),
                                                                            ],
                                                                            help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "body",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "card_clickable",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "heading",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_level",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            default=3,
                                                                            help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                            max_value=6,
                                                                            min_value=2,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_size",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "",
                                                                                    "Default",
                                                                                ),
                                                                                (
                                                                                    "small",
                                                                                    "Small",
                                                                                ),
                                                                                (
                                                                                    "medium",
                                                                                    "Medium",
                                                                                ),
                                                                                (
                                                                                    "large",
                                                                                    "Large",
                                                                                ),
                                                                            ],
                                                                            help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "body",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "internal_page",
                                                                        wagtail.blocks.PageChooserBlock(
                                                                            help_text="Interal Page Link for the card",
                                                                            label="Internal Page",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "url",
                                                                        wagtail.blocks.URLBlock(
                                                                            help_text="External Link for the card",
                                                                            label="URL",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "card_image",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "heading",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_level",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            default=3,
                                                                            help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                            max_value=6,
                                                                            min_value=2,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_size",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "",
                                                                                    "Default",
                                                                                ),
                                                                                (
                                                                                    "small",
                                                                                    "Small",
                                                                                ),
                                                                                (
                                                                                    "medium",
                                                                                    "Medium",
                                                                                ),
                                                                                (
                                                                                    "large",
                                                                                    "Large",
                                                                                ),
                                                                            ],
                                                                            help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "body",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "content_image",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            label="Image",
                                                                            required=True,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "alt_text",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "url",
                                                                        wagtail.blocks.URLBlock(
                                                                            help_text="Optional, if there is a link the entire card will be clickable.",
                                                                            label="URL",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "internal_page",
                                                                        wagtail.blocks.PageChooserBlock(
                                                                            help_text="Optional, if there is a link the entire card will be clickable.",
                                                                            label="Internal Page",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "card_feature",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "feature_heading",
                                                                        wagtail.blocks.CharBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_level",
                                                                        wagtail.blocks.IntegerBlock(
                                                                            default=3,
                                                                            help_text="The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.",
                                                                            max_value=6,
                                                                            min_value=2,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "heading_size",
                                                                        wagtail.blocks.ChoiceBlock(
                                                                            choices=[
                                                                                (
                                                                                    "",
                                                                                    "Default",
                                                                                ),
                                                                                (
                                                                                    "small",
                                                                                    "Small",
                                                                                ),
                                                                                (
                                                                                    "medium",
                                                                                    "Medium",
                                                                                ),
                                                                                (
                                                                                    "large",
                                                                                    "Large",
                                                                                ),
                                                                            ],
                                                                            help_text="The heading size affects the visual size, this follows the front-end library's sizing.",
                                                                            required=False,
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "body",
                                                                        wagtail.blocks.RichTextBlock(
                                                                            required=True
                                                                        ),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                    ],
                                                    required=True,
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                ]
            ),
        ),
    ]
