# Generated by Django 4.0.8 on 2023-03-29 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_alter_campaignupdate_image_alt_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"permissions": [("unpublish", "Can unpublish a published page")]},
        ),
    ]
