# Generated by Django 5.0.9 on 2024-11-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_alter_rendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description"
            ),
        ),
    ]
