# Generated by Django 3.1.8 on 2021-04-21 14:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    ("paragraph", wagtail.core.blocks.RichTextBlock()),
                    (
                        "left_image_with_text",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("title", wagtail.core.blocks.CharBlock()),
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        features=["bold", "italic"]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "accordion",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("title", wagtail.core.blocks.CharBlock()),
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        features=["bold", "italic", "link"]
                                    ),
                                ),
                                (
                                    "show_numbering",
                                    wagtail.core.blocks.BooleanBlock(
                                        help_text="Controls whether to show numbers next to the accordion items.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "items",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.core.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.core.blocks.CharBlock(),
                                                ),
                                                (
                                                    "text",
                                                    wagtail.core.blocks.TextBlock(),
                                                ),
                                            ],
                                            icon="pilcrow",
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "text_with_image_stack",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("title", wagtail.core.blocks.CharBlock()),
                                (
                                    "text",
                                    wagtail.core.blocks.RichTextBlock(
                                        features=["bold", "italic", "link"]
                                    ),
                                ),
                                (
                                    "images",
                                    wagtail.core.blocks.ListBlock(
                                        wagtail.images.blocks.ImageChooserBlock()
                                    ),
                                ),
                            ]
                        ),
                    ),
                ]
            ),
        ),
    ]
