# Generated by Django 3.1.13 on 2021-10-04 11:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_customimage_file_hash"),
        ("standardpages", "0003_auto_20210817_1138"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "informationpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="standardpages.informationpage",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        help_text="Introduction section for the resource page"
                    ),
                ),
                (
                    "summary",
                    wagtail.fields.RichTextField(
                        help_text="Short line of text for display on the campaign page"
                    ),
                ),
                ("image_alt_text", models.TextField(blank=True)),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("standardpages.informationpage",),
        ),
    ]
