# Generated by Django 3.1.13 on 2021-12-15 11:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('standardpages', '0007_auto_20211213_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('left_image_with_text', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_alt_text', wagtail.core.blocks.CharBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic']))])), ('accordion', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'])), ('show_numbering', wagtail.core.blocks.BooleanBlock(help_text='Controls whether to show numbers next to the accordion items.', required=False)), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock())], icon='pilcrow')))])), ('text_with_image_stack', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('heading_level', wagtail.core.blocks.IntegerBlock(default=3, help_text='The heading level affects users with screen readers. Ignore this if there is no label. Default=3, Min=2, Max=6.', max_value=6, min_value=2)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))]))], blank=True),
        ),
    ]
