# Generated by Django 4.0.8 on 2023-03-29 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("standardpages", "0009_alter_aboutpage_image_alt_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutpage",
            options={"permissions": [("unpublish", "Can unpublish a published page")]},
        ),
        migrations.AlterModelOptions(
            name="indexpage",
            options={"permissions": [("unpublish", "Can unpublish a published page")]},
        ),
        migrations.AlterModelOptions(
            name="informationpage",
            options={"permissions": [("unpublish", "Can unpublish a published page")]},
        ),
    ]
