# Generated by Django 4.0.10 on 2023-08-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("standardpages", "0011_alter_informationpage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationpage",
            name="no_index_toggle",
            field=models.BooleanField(
                default=False, help_text="Exclude file from being indexed by Google"
            ),
        ),
    ]
