# Generated by Django 4.0.10 on 2023-09-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("standardpages", "0012_informationpage_no_index_toggle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationpage",
            name="no_index_toggle",
            field=models.BooleanField(
                default=False,
                help_text="Exclude file from being indexed by Google",
                verbose_name="no index toggle",
            ),
        ),
    ]
