# Generated by Django 3.1.11 on 2021-07-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSequenceNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seq_number', models.IntegerField()),
                ('order_number', models.CharField(max_length=30)),
            ],
        ),
    ]
