# Generated by Django 3.1.13 on 2021-12-08 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ordersequencenumber",
            unique_together={("date", "seq_number")},
        ),
    ]
