# Generated by Django 3.1.11 on 2021-07-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParagonUserAdmin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "manage_paragon_users",
                        "Can view Paragon users and change access level",
                    ),
                    (
                        "manage_paragon_users_all_fields",
                        "Can view Paragon users and change all details",
                    ),
                ],
                "default_permissions": [],
            },
        ),
    ]
