# Generated by Django 3.1.13 on 2021-07-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paragon_users", "0002_change_permission_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_token", models.CharField(max_length=256)),
                ("email", models.CharField(max_length=256)),
                ("url", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="VerificationEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_token", models.CharField(max_length=256)),
                ("email", models.CharField(max_length=256)),
                ("url", models.CharField(max_length=256)),
                ("first_name", models.CharField(max_length=256)),
            ],
        ),
    ]
