name: Node Continuous Integration

on:
  push:
    branches:
      - 'main'
      - 'review/*'
      - 'refs/tags/*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Extract branch name'
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/})"
      shell: bash
      id: extract_branch