parameters:
  - name: environment # environemnt to deploy to
    type: string
    values:
      - dev
      - int
      - stag
      - prod
  - name: azureSubscription # the service connection in the pipeline
    type: string
  - name: tfResourceGroup # name of the resource group which stores the TF state
    type: string
  - name: tfStorageAccount # name of the storage account which stores the TF state
    type: string
  - name: dryrun # skip apply stage
    type: boolean
    default: false
  - name: location # location of the resources
    type: string
    default: uks
  - name: workingDirectory
    type: string
    default: $(Pipeline.Workspace)/terraform

steps:
  - checkout: network-spoke
    persistCredentials: true
    fetchDepth: 1

  - checkout: container-app-env
    persistCredentials: true
    fetchDepth: 1

  - checkout: wagtail-container-apps
    persistCredentials: true
    fetchDepth: 1

  - script: |
      tail -n 2 $(Pipeline.Workspace)/s/nhsuk.platform.terraform-modules.network-spoke/.git/config >> ~/.gitconfig
      tail -n 2 $(Pipeline.Workspace)/s/dct.terraform-modules.container-app-env/.git/config >> ~/.gitconfig
      tail -n 2 $(Pipeline.Workspace)/s/dct.terraform-modules.wagtail-container-apps/.git/config >> ~/.gitconfig
    displayName: Git auth

  - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@2
    displayName: Install latest Terraform

  - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@2
    displayName: terraform init
    inputs:
      command: init
      workingDirectory: ${{ parameters.workingDirectory }}
      backendType: azurerm
      backendServiceArm: ${{ parameters.azureSubscription }}
      backendAzureRmResourceGroupName: ${{ parameters.tfResourceGroup }}
      backendAzureRmStorageAccountName: ${{ parameters.tfStorageAccount }}

  - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@2
    displayName: terraform plan
    inputs:
      command: plan
      workingDirectory: ${{ parameters.workingDirectory }}
      environmentServiceName: ${{ parameters.azureSubscription }}
      publishPlanResults: ${{ parameters.environment }}_deployment_plan
      commandOptions: >
        -var-file="env/${{ parameters.environment }}-${{ parameters.location }}.tfvars"
        -out=$(System.DefaultWorkingDirectory)/terraform.tfplan
        -detailed-exitcode
        -lock=false
    ${{ if or(eq(parameters.environment, 'int'), eq(parameters.environment, 'stag')) }}:
      env:
        TF_VAR_sha_512_password: $(SHA_512_PASSWORD)

  - ${{ if eq(parameters.dryrun, 'true') }}:
    - bash: |
        echo "##vso[task.logissue type=warning;]Running in dryrun mode - skipping apply step"
        echo "##vso[task.complete result=SucceededWithIssues;]"
      displayName: Dry Run - skipping apply

  - ${{ if ne(parameters.dryrun, 'true') }}:
    - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@2
      displayName: terraform apply
      condition: and(succeeded(), eq(variables['TERRAFORM_PLAN_HAS_CHANGES'], 'true'))
      inputs:
        command: apply
        workingDirectory: ${{ parameters.workingDirectory }}
        environmentServiceName: ${{ parameters.azureSubscription }}
        commandOptions: $(System.DefaultWorkingDirectory)/terraform.tfplan

  - task: AzureCLI@2
    displayName: Azure CLI check secrets
    condition: succeededOrFailed()
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        secretIds=$(az keyvault secret list --vault-name dct-crccms-kv2-${{ parameters.environment }}-${{ parameters.location }} --query [].id)
        secretIds=$(echo $secretIds | jq -c '.[]' | awk '{gsub(/"/,"")}1')
        emptySecrets=""

        for secretId in ${secretIds[@]};
        do
          secretName=$(echo $secretId | awk -F'/' '{print $NF}')
          secretValue=$(az keyvault secret show --id $secretId --query value)
          secretValue=$(echo $secretValue | awk '{gsub(/"/,"")}1')
          if [[ $secretValue == '' ]];
          then
            echo "WARNING: $secretName has no value"
            emptySecrets="${emptySecrets} ${secretName}"
          else
            echo "SUCCESS: $secretName has a value"
          fi
        done

        if [[ $emptySecrets != '' ]];
        then
          echo "##vso[task.logissue type=warning;]Empty secrets found in dct-crccms-kv2-${{ parameters.environment }}-${{ parameters.location }}: [$emptySecrets ]"
          echo "##vso[task.complete result=SucceededWithIssues;]"
        fi
